version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: dogs-postgres
    environment:
      POSTGRES_DB: dogsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
