INSERT INTO breed (name) VALUES
('Affenpinscher'),
('African'),
('Airedale'),
('Akita'),
('Appenzeller'),
('Australian Shepherd'),
('Basenji'),
('Beagle'),
('Bluetick'),
('Borzoi'),
('Bouvier'),
('Boxer'),
('Brabancon'),
('Briard'),
('Norwegian Buhund'),
('Boston Bulldog'),
('English Bulldog'),
('French Bulldog'),
('Staffordshire Bullterrier'),
('Australian Cattledog'),
('Chihuahua'),
('Chow'),
('Clumber'),
('Cockapoo'),
('Border Collie'),
('Coonhound'),
('Cardigan Corgi'),
('Cotondetulear'),
('Dachshund'),
('Dalmatian'),
('Great Dane'),
('Scottish Deerhound'),
('Dhole'),
('Dingo'),
('Doberman'),
('Norwegian Elkhound'),
('Entlebucher'),
('Eskimo'),
('Finnish Lapphund'),
('Bichon Frise'),
('German Shepherd'),
('Italian Greyhound'),
('Groenendael'),
('Havanese'),
('Afghan Hound'),
('Basset Hound'),
('Blood Hound'),
('English Hound'),
('Ibizan Hound'),
('Plott Hound'),
('Walker Hound'),
('Husky'),
('Keeshond'),
('Kelpie'),
('Komondor'),
('Kuvasz'),
('Labradoodle'),
('Labrador'),
('Leonberg'),
('Lhasa'),
('Malamute'),
('Malinois'),
('Maltese'),
('Bull Mastiff'),
('English Mastiff'),
('Tibetan Mastiff'),
('Mexicanhairless'),
('Mix'),
('Bernese Mountain'),
('Swiss Mountain'),
('Newfoundland'),
('Otterhound'),
('Caucasian Ovcharka'),
('Papillon'),
('Pekinese'),
('Pembroke'),
('Miniature Pinscher'),
('Pitbull'),
('German Pointer'),
('Germanlonghair Pointer'),
('Pomeranian'),
('Medium Poodle'),
('Miniature Poodle'),
('Standard Poodle'),
('Toy Poodle'),
('Pug'),
('Puggle'),
('Pyrenees'),
('Redbone'),
('Chesapeake Retriever'),
('Curly Retriever'),
('Flatcoated Retriever'),
('Golden Retriever'),
('Rhodesian Ridgeback'),
('Rottweiler'),
('Saluki'),
('Samoyed'),
('Schipperke'),
('Giant Schnauzer'),
('Miniature Schnauzer'),
('Italian Segugio'),
('English Setter'),
('Gordon Setter'),
('Irish Setter'),
('English Sheepdog'),
('Shetland Sheepdog'),
('Shiba'),
('Shihtzu'),
('Blenheim Spaniel'),
('Brittany Spaniel'),
('Cocker Spaniel'),
('Irish Spaniel'),
('Japanese Spaniel'),
('Sussex Spaniel'),
('Welsh Spaniel'),
('Japanese Spitz'),
('English Springer'),
('Stbernard'),
('American Terrier'),
('Australian Terrier'),
('Bedlington Terrier'),
('Border Terrier'),
('Cairn Terrier'),
('Dandie Terrier'),
('Fox Terrier'),
('Irish Terrier'),
('Kerryblue Terrier'),
('Lakeland Terrier'),
('Norfolk Terrier'),
('Norwich Terrier'),
('Patterdale Terrier'),
('Russell Terrier'),
('Scottish Terrier'),
('Sealyham Terrier'),
('Silky Terrier'),
('Tibetan Terrier'),
('Toy Terrier'),
('Welsh Terrier'),
('Westhighland Terrier'),
('Wheaten Terrier'),
('Yorkshire Terrier'),
('Tervuren'),
('Vizsla'),
('Spanish Waterdog'),
('Weimaraner'),
('Whippet'),
('Irish Wolfhound');
